import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})

export class WordsService {
  private words: string[] = [
    'linde',
    'ava',
    'papa',
    'mama',
    'stephanie',
    'joran',
    'saga',
    'amon',
    'seppe'
    // 'appel',
    // 'peren',
    // 'banaan',
    // 'sinaasappel',
    // 'peer',
    // 'kers',
    // 'druif',
    // 'mandarijn',
    // 'ananas',
    // 'kokosnoot',
    // 'watermeloen',
    // 'kersen',
    // 'framboos',
    // 'aardbei',
    // 'blauwe bessen',
    // 'zwarte bessen',
    // 'braambes',
    // 'kaki',
    // 'mango',
    // 'papaja',
    // 'kiwi',
    // 'lychee',
    // 'passievrucht',
    // 'granaatappel',
    // 'avocado',
    // 'olijf',
    // 'komkommer',
    // 'tomaat',
    // 'wortel',
    // 'ui',
    // 'prei',
    // 'spinazie',
    // 'sla',
    // 'kool',
    // 'boontje',
    // 'erwt',
    // 'linzen',
    // 'tarwe',
    // 'gerst',
    // 'haver',
    // 'rogge',
    // 'maïs',
    // 'rijst',
    // 'aardappel',
    // 'vlees',
    // 'vis',
    // 'kip',
    // 'eend',
    // 'kalf',
    // 'varken',
    // 'kipfilet',
    // 'visfilet',
    // 'kalfsvlees',
    // 'varkensvlees',
    // 'brood',
    // 'boter',
    // 'kaas',
    // 'ei',
    // 'melk',
    // 'yoghurt',
    // 'ijs',
    // 'snoep',
    // 'chocolade',
    // 'snoepgoed',
    // 'bonbons',
    // 'drop',
    // 'ijsje',
    // 'koek',
    // 'gebak',
    // 'taart',
    // 'appeltaart',
    // 'krentenbol',
    // 'krentenbrij',
    // 'pannenkoek',
    // 'wafel',
    // 'ijsroom',
    // 'slagroom',
    // 'boterham',
    // 'broodje',
    // 'sandwich',
    // 'hamburger',
    // 'hotdog',
    // 'pizza',
    // 'pasta',
    // 'lasagne',
    // 'spaghetti',
    // 'macaroni',
];


constructor() {}

    getRandomWord(): string {
    const randomIndex = Math.floor(Math.random() * this.words.length);
    return this.words[randomIndex];
    }
}
